In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7592, 5689, 1463, 2014],
 [7592, 5689, 1463, 1491],
 [7592, 3334, 1463, 7716],
 [2096, 1592, 8546, 1185, 3496],
 [2096, 1592, 8546, 1185, 7021],
 [4396, 7592, 7727, 1463, 2314],
 [6021, 9310, 5146, 1185]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7592 5689 1463 2014]
 [   0    0    0    0 7592 5689 1463 1491]
 [   0    0    0    0 7592 3334 1463 7716]
 [   0    0    0 2096 1592 8546 1185 3496]
 [   0    0    0 2096 1592 8546 1185 7021]
 [   0    0    0 4396 7592 7727 1463 2314]
 [   0    0    0    0 6021 9310 5146 1185]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Python312\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [29]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [30]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step


array([[[ 4.2151775e-02, -2.5089372e-02,  2.2773329e-02,  4.0451299e-02,
         -2.1114171e-02,  3.4020606e-02, -2.7075684e-02,  1.1766445e-02,
          3.9552581e-02, -3.1809583e-02],
        [ 4.2151775e-02, -2.5089372e-02,  2.2773329e-02,  4.0451299e-02,
         -2.1114171e-02,  3.4020606e-02, -2.7075684e-02,  1.1766445e-02,
          3.9552581e-02, -3.1809583e-02],
        [ 4.2151775e-02, -2.5089372e-02,  2.2773329e-02,  4.0451299e-02,
         -2.1114171e-02,  3.4020606e-02, -2.7075684e-02,  1.1766445e-02,
          3.9552581e-02, -3.1809583e-02],
        [ 4.2151775e-02, -2.5089372e-02,  2.2773329e-02,  4.0451299e-02,
         -2.1114171e-02,  3.4020606e-02, -2.7075684e-02,  1.1766445e-02,
          3.9552581e-02, -3.1809583e-02],
        [ 1.8115509e-02, -3.2944284e-02,  4.2534087e-02,  1.6284894e-02,
         -3.8524736e-02,  3.3344839e-02, -2.5942374e-02,  2.9779971e-05,
          4.9618993e-02,  2.1535996e-02],
        [-3.4491204e-02,  1.7536569e-02, -2.1226931e-02,  1.

In [31]:
embedded_docs[0]

array([   0,    0,    0,    0, 7592, 5689, 1463, 2014], dtype=int32)